In [1]:
import numpy as np
import argopy
from argopy import DataFetcher
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import gsw
from datetime import datetime
from cartopy.geodesic import Geodesic
from scipy import linalg
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, WhiteKernel, ConstantKernel as C
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import haversine_distances
from matplotlib.patches import Circle

import ArgoHeatContentDataCollater as ahdc
import ArgoGPR as ag
import seaborn as sns
from scipy import stats

In [2]:
# 1. LOAD DATA
# Adjust path to your folder
df_argo = ahdc.load_argo_data_advanced(
    nc_dir='/home/avik2007/ArgoEBUSAnalysis/ArgoData/', 
    start_date='2017-01-01', 
    end_date='2019-01-01', # Grab a few months to test
    lat_bounds=[30, 40], 
    lon_bounds=[-126, -119],
    depth_bounds = [0, 500],
)

📂 FOUND LOCAL DATASET: /home/avik2007/ArgoEBUSAnalysis/ArgoData/argo_2017-01-01_to_2019-01-01_lat30_40_lon-126_-119_z0_500.pkl
   Loading processed DataFrame...
   ✅ Loaded 70432 profile measurements from disk.

In [3]:
df_argo

,N_POINTS,temp,psal,pres,lat,lon,date,float_id,depth,time_days
895,895,16.319000,33.300610,4.300000,33.98700,-124.70500,2017-01-05 17:15:11,4900832,4.269287,4.718877
896,896,16.291000,33.299450,9.400000,33.98700,-124.70500,2017-01-05 17:15:11,4900832,9.332745,4.718877
897,897,16.285000,33.298409,16.400000,33.98700,-124.70500,2017-01-05 17:15:11,4900832,16.282384,4.718877
898,898,16.288000,33.299419,23.299999,33.98700,-124.70500,2017-01-05 17:15:11,4900832,23.132512,4.718877
899,899,16.287001,33.299450,30.100000,33.98700,-124.70500,2017-01-05 17:15:11,4900832,29.883140,4.718877
...,...,...,...,...,...,...,...,...,...,...
54642,54642,5.741000,34.141399,492.040009,37.06362,-124.90991,2018-05-13 09:58:17,5904378,487.819023,497.415475
54643,54643,5.730000,34.140301,494.000000,37.06362,-124.90991,2018-05-13 09:58:17,5904378,489.759890,497.415475
54644,54644,5.719000,34.142502,495.959991,37.06362,-124.90991,2018-05-13 09:58:17,5904378,491.700739,497.415475
54645,54645,5.724000,34.147499,497.920013,37.06362,-124.90991,2018-05-13 09:58:17,5904378,493.641600,497.415475
54646,54646,5.710000,34.148701,499.880005,37.06362,-124.90991,2018-05-13 09:58:17,5904378,495.582412,497.415475

In [7]:
df_ohc_500m = ahdc.estimate_ohc_from_raw_bins(df_argo, depth_max = 5000, resolution_lat=0.05, resolution_lon = 0.05, min_coverage_pct= 0.5)

📦 BINNING RAW DATA: 0.05° x 0.05° x 30 days...
   ... Grouping and Integrating (Layer: 0-5000m)...
✅ DONE. Generated 0 valid bin estimates.

In [5]:
df_ohc_500m

Empty DataFrame
Columns: [time_bin, lat_bin, lon_bin, ohc, n_raw_points]
Index: []